{
 "title": "Flask Counter App + Redis + Containers",
 "tags": [
  "flask",
  "redis",
  "practice"
 ],
 "refresh": "5s",
 "panels": [
  {
   "title": "Requests Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "sum(app_requests_total)", "legendFormat": "total" }
   ]
  },
  {
   "title": "Errors Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "targets": [
    { "expr": "sum(app_errors_total)", "legendFormat": "errors" }
   ]
  },
  {
   "title": "Request Latency p95 (сек)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(app_request_latency_seconds_bucket[5m])) by (le))",
     "legendFormat": "p95"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "targets": [
    { "expr": "rate(app_requests_total[1m])", "legendFormat": "RPS" }
   ]
  },
  {
   "title": "Redis Memory (MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "redis_memory_used_bytes / 1024 / 1024",
     "legendFormat": "used MB"
    }
   ]
  },
  {
   "title": "Container CPU %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 12 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{name=~\"web.*\"}[5m]) * 100",
     "legendFormat": "web CPU %"
    }
   ]
  },
  {
   "title": "Redis Connected Clients",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 12 },
   "targets": [
    { "expr": "redis_connected_clients", "legendFormat": "clients" }
   ]
  }
 ]
}